[package]
name = "kips_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.0"
rusb = "0.9"
sdl2 = { version = "0.35", features = ["ttf", "image"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
