# Cargo.toml
[package]
name = "pi_tablet"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.14.0"
sdl2 = { version = "0.35.2", features = ["ttf", "image", "static-link"] }
gif = "0.11.4"
crossbeam-channel = "0.5.0"
lazy_static = "1.4.0"